<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "workspace_test"
 *
 * Auto generated by Extension Builder 2013-04-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Workspace test extension',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Timo Webler',
	'author_email' => 'timo.webler@dkd.de',
	'author_company' => 'dkd Internet Service GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>